### ISSUE TITLE
I get and PHP error use of undefined constant_name file_name

### ISSUE THREAD

**Issue by tanki7** [gmansillo/simple#109]
I'm submitting a bug report regarding the firepower joomla component, after installation i created a menu that is listing the category of documents, My uploaded document types are PDF and DOCX.

When i want to browse the documents it shows me
Notice: Use of undefined constant file_name - assumed 'file_name' in C:\wamp64\www\website\components\com_firedrive\views\document\view.raw.php on line 56

Warning: finfo::file(file_name): failed to open stream: No such file or directory in C:\wamp64\www\khaia-final\components\com_firedrive\views\document\view.raw.php on line 56

. Even i thought this will be fixed by uploading online to hosting providers. It's the same. 

What should be done?

The version of Firedrive I'm using is 5.2.3 is the latest Joomla version 3.8.5 and PHP 7.0.10 and MySQL 5.7
No it happens in all browsers.

![image](https://user-images.githubusercontent.com/44396746/47351345-1174e480-d6b8-11e8-8f9f-b7cc9ba656bb.png)

**Comment by gmansillo** [comment]
Hi @tanki7, thanks for reporting.
This is a known issue that will be fixed in the next update, soon available. In the meanwhile you can edit your C:\wamp64\www\khaia-final\components\com_firedrive\views\document\view.raw.php on line 56 replacing the string `file_name` with `$item->file_name`.

Hope it helps,
Giovanni

**Comment by gmansillo** [comment]
Solved in commit bef4dac43180d1648e787574239cbce739c76352.
Definitive fix will be available in next release.
