### ISSUE TITLE
Error after update to last version

### ISSUE THREAD

**Issue by Babbicciu** [gmansillo/simple#19]
Hi, this is the Error it shows after last update of simple file manager, sorry to bother you: is it something I have to solve in my Joomla setup or is it connected with something due to SFM?

Ciao, questo errore mi compare dopo l'ultimo aggiornamento, non voglio apparire come un rompiscatole ma solo capire se è qualcosa che dipende da qualche setting del mio Joomla o dall'aggiornamento stesso. Per la precedente versione avevo fatto la donazione, mi trovo davvero bene, ora procedo con la nuova donazione, ma spero tu possa aiutarmi a risolvere il malfunzionamento. Un saluto

![untitled-1](https://cloud.githubusercontent.com/assets/19651052/15712372/65a1801a-2812-11e6-9904-1e00423b970c.jpg)

Errore

Unknown column 'a.reserved_group' in 'field list' SQL=SELECT a.id, a.title, a.catid,a.state, a.featured,a.publish_up, a.publish_down, a.ordering,a.checked_out, a.checked_out_time,a.download_counter, a.download_last, a.file_created, a.file_name, a.reserved_user, a.reserved_group, a.visibility, a.author,c.title AS category_title,uc.name AS editor FROM `#__simplefilemanager` AS a LEFT JOIN #__categories AS c ON c.id = a.catid LEFT JOIN #__users AS uc ON uc.id=a.checked_out WHERE (a.state IN (0, 1)) ORDER BY c.title asc, a.ordering asc LIMIT 0, 20

**Comment by gmansillo** [comment]
Hi Babicciu, probably you updated your SFM version with an incompatible package (e.g. 4.3.x with 5.0.8). You should restore a backup (or reinstall the previous version) to recover your installation and to make it work again. Otherwise, if you want to upgrade to SFM 5, you have to make a new installation losing all your previous entries.
If you supported the development of SFM 4 with a donation, please  write me an email with the account registered on paypal and i'll be glad to send you and up-to-date installation package.
