### ISSUE TITLE
Editing from frontend, unpublishes file

### ISSUE THREAD

**Issue by ghost** [gmansillo/simple#58]
Hi

When editing a document from frontend the files becomes unpublished.
This happens no matter what the edit is - replacing file, changing description - the document changes state to unpublished.

(Joomla 3.7.0, Simple File Manager 5.0.12)

**Comment by gmansillo** [comment]
Hi,
thank you for reporting this issue, it helps me improving the extension.
Are you editing files as an admin or as a common user?

**Comment by ghost** [comment]
As a common, registered user.



Den 4. maj 2017 21.59 skrev "Giovanni" <notifications@github.com>:

**Comment by gmansillo** [comment]
This is the expected behaviour: registred users cannot edit items without administrator permission. As in other joomla components, when a user edits something, the administrator has to republish the item to make it visible again. 
If you want users able to edit their documents without administrator interaction, you need to edit joomla acls.
Anyway, this part in Simple may have some bugs that need to be fixed since this is a recent feature. If you encounter one of them please let me know!

**Comment by ghost** [comment]
Thanks for the answer :)

2017-05-05 18:32 GMT+02:00 Giovanni <notifications@github.com>:
