### ISSUE TITLE
Update to 5.1.2p MASSIVE FAIL!!!

### ISSUE THREAD

**Issue by ChasLarge** [gmansillo/simple#67]
Hi, Just got prompted to install SFM 5.1.2p have 5.0.12 installed already. Several problems:

1. Category lists now empty with error message:
Warning: array_merge(): Argument #2 is not an array in /home/mywebsitename/public_html/components/com_simplefilemanager/helpers/simplefilemanager.php on line 35

2. Component name in Admin backend changed from "Simple File Manager" to "Documents"

3. After install of update, repeatedly prompted to install the same mod again, this time showing 5.1.2 installed and offering 5.1.2p again.

Only way to restore operation is to uninstall and reinstall 5.0.12 but then have to reupload all files again as the database links have been lost.

Very disappointing and frustrating.

PLEASE TEST THOROUGHLY BEFORE RELEASING THE NEXT UPDATE!

**Comment by gmansillo** [comment]
Hi @ChasLarge,
where do you encounter the error described in the first point?
Point n.2 is the desired effect. I wanted to help final users understanding Simple's tasks.
I'm sorry for the issue in point n.3. I think it's due to a misconfiguration in simple's xml manifest and I'm gooing to fix it immediately.

**Comment by ChasLarge** [comment]
Hi,

Point 1 appears when installing the update if you have 5.0.12 installed already, the catgories are lost and have to be recreated.

Point 2 is confusing as I expected to see Simple File Manager in the list of components, documents did not mean anything to me as I put files like sofwear and pictures and videos, not documents for the users to download.

If it helps, am using latest Joomla on server running php 7.1

**Comment by gmansillo** [comment]
The fact that you are using the latest version of Joomla! make me think that you stumbled onto this Joomla!'s issue: https://forum.joomla.org/viewtopic.php?t=949942
You have to add superusers to all access levels in order to came back seeing all categories in backend dropdowns.

I'm interested in finding a solution to the warning you reported me:
`Warning: array_merge(): Argument #2 is not an array in /home/mywebsitename/public_html/components/com_simplefilemanager/helpers/simplefilemanager.php on line 35`
Where did you get it exactly?

**Comment by gmansillo** [comment]
About point 2, in any moment you can change Simple's text strings: just make an [override](https://docs.joomla.org/J3.x:Language_Overrides_in_Joomla) and you'll never lost your customizations

**Comment by ChasLarge** [comment]
Dear Giovanni,

 

No, I do not have this problem.

 

Trying to reproduce this issue, I must have recorded that issue after I uninstalled the software in an effort to repair the faulty installing and the changes to the Admin > Components > SFM labelling.

 

I have just tried again the update on another test server and this has worked correctly but of course you have now changed the update back to 5.0.12p so the issue cannot be reproduced anyway.

 

Either way it would have proved disastrous on a clients system where I have spent weeks installing and uploading files. There should ideally be a facility to backup and restore the settings of the documents just in case some other issue causes them to become lost or corrupted.

 

Another request would be a SAVE & NEW button for documents like there is in categories as it is more likely to be needed when uploading documents than categories. 

 

Hope this helps.

 

 

Regards

Chas

 

 <http://www.chas-large.co.uk/> 
Chas Large - Web Design, Management & Electronic Documentation.

07730 538 697 www.chas-large.co.uk <http://www.chas-large.co.uk>

**Comment by ChasLarge** [comment]
Yes, I appreciate you can do this but your original component title Simple File Manager is the name of the application, changing this to Documents is confusing. Maybe Documents Manager might be an alternative?

 

 

Regards

Chas

 

 <http://www.chas-large.co.uk/> 
Chas Large - Web Design, Management & Electronic Documentation.

07730 538 697 www.chas-large.co.uk <http://www.chas-large.co.uk>

**Comment by gmansillo** [comment]
I'll think to the facility that you suggest. Also other users suggested it in the past.

Of course I edited Simple's xml manifest after you reported the issue but it is has nothing to do with the warning that you posted.

Save and new button is already in Simple 5.1.2.

Since you don't see the warning at point 1, you know how to change the component name in admin menu and the update issue at point 3 has been fixed, I think there isn't any other technical issue in this topic to be fixed, so the "Massive fail" that you claim can be considered extinguished and i'm going to close the issue. Please open another topic for reporting new technical issues.

Thank you.
