### ISSUE TITLE
Bad module position

### ISSUE THREAD

**Issue by Filipv82** [gmansillo/simple#85]
All worked fine but after installation of the newest version, the module is positioned badly and I can't fix it. Where in the css can I change the module size?
For example: http://adl2000.be/index.php/2015-09-10-20-23-43/afdeling-b/wedstrijduitslag-b

Thx in advance.

**Comment by gmansillo** [comment]
Hi @Filipv82 ,
in your template's css folder there is a jstuff.css file with the following rule starting at line 673:
```
#modules-form .btn-group, #adminForm .btn-group {
    right: auto;
    margin-left: 0;
}
```
I noticed that commenting  the `right: auto;` your problem disappears.

Instead of commenting this line, you can add a new rule somewhere in order to override this behaviour. For example you can add this line of code:

`#sfm-category-list #adminForm .btn-group { right: 0; } `
